FROM debian:stable-20230522

WORKDIR "/redis"

COPY . .

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install lsb-release curl gpg wget build-essential -y
RUN wget http://download.redis.io/redis-stable.tar.gz && tar -xvzf redis-stable.tar.gz
RUN mkdir /etc/redis && mkdir /var/redis && mkdir /var/redis/6379

WORKDIR "/redis/redis-stable"

RUN make
RUN make install
RUN cp /redis/redis_init_script /etc/init.d/redis_6379 && cp /redis/redis.conf /etc/redis/6379.conf
RUN update-rc.d redis_6379 defaults

EXPOSE 6379

ENTRYPOINT [ "/etc/init.d/redis_6379", "start" ]

# FROM debian:stable-20230522

# RUN apt-get update && apt install -y lsb-release curl gpg

# RUN curl -fsSL https://packages.redis.io/gpg |  gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

# RUN echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/redis.list

# RUN apt-get update && apt-get install -y redis

# COPY redis.conf /usr/local/etc/redis/redis.conf

# CMD ["redis-server","/usr/local/etc/redis/redis.conf"]
